name: CI

on:
  pull_request:
    branches:
      - main
      - "feature/*"

  push:
    branches:
      - main

jobs:

  client:
    name: Client Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install client deps
        working-directory: client
        run: npm ci

      - name: Lint client
        working-directory: client
        run: npm run lint

      - name: Build client
        working-directory: client
        run: npm run build


  server:
    name: Server Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install server deps
        working-directory: server
        run: npm ci

      - name: Generate Prisma client
        working-directory: server
        run: npx prisma generate

      - name: Validate Prisma schema
        working-directory: server
        run: npx prisma validate

      - name: Build server
        working-directory: server
        run: npm run build