name: CI

on:
  pull_request:
    branches:
      - main
      - 'feature/*'
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      # CLIENT
      - name: Install client dependencies
        run: |
          cd client
          npm ci

      - name: Lint client
        run: |
          cd client
          npm run lint

      - name: Build client
        run: |
          cd client
          npm run build

      # SERVER
      - name: Install server dependencies
        run: |
          cd server
          npm ci

      - name: Generate Prisma client
        run: |
          cd server
          npx prisma generate

      - name: Build server
        run: |
          cd server
          npm run build